version: "3"
services: 
  db:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: potfolly2_development
      # MYSQL_USER: 'user'
      # MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - .:/myapp
      - bundle:/usr/local/bundle
    ports: 
      - "3000:3000"
    environment: 
      DB_PORT: 3306
      DB_HOST: db
    depends_on: 
      - db
    stdin_open: true
    tty: true
    # command: bundle exec rails server -b 0.0.0.0

volumes: 
  mysql-data:
  bundle: